PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    problem_on_unmodified_line: ignore # run RuboCop only on modified code
    command: ["bundle", "exec", "rubocop"]
